language: go
go:
 - "1.11.x"

os: osx

install: true

env:
  global:
    - CODECOV_TOKEN="4577e6e0-0592-4dc3-a6b6-01fa26d5ef7e"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)